<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="33340" started-at="2021-03-08T05:02:58Z" finished-at="2021-03-08T05:03:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="33340" started-at="2021-03-08T05:02:58Z" finished-at="2021-03-08T05:03:32Z">
      <class name="webdriver.Corpweb_footer">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:webdriver.Corpweb_footer@51081592]" name="beforeClass" is-config="true" duration-ms="4179" started-at="2021-03-08T05:02:58Z" finished-at="2021-03-08T05:03:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="TC_02_Footer_Network()[pri:0, instance:webdriver.Corpweb_footer@51081592]" name="TC_02_Footer_Network" duration-ms="28272" started-at="2021-03-08T05:03:03Z" finished-at="2021-03-08T05:03:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Vinamilk Baby Care - Trang chủ | Facebook] but found [Đăng nhập Facebook | Facebook]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Vinamilk Baby Care - Trang chủ | Facebook] but found [Đăng nhập Facebook | Facebook]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at webdriver.Corpweb_footer.TC_02_Footer_Network(Corpweb_footer.java:213)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_02_Footer_Network -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:webdriver.Corpweb_footer@51081592]" name="afterClass" is-config="true" duration-ms="854" started-at="2021-03-08T05:03:31Z" finished-at="2021-03-08T05:03:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- webdriver.Corpweb_footer -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
